# Generated by Django 4.1.7 on 2023-03-12 01:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_db',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('e_mail', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('preferred_language', models.CharField(max_length=10)),
            ],
        ),
    ]
