# Generated by Django 4.1.7 on 2023-03-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=50)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
