# Generated by Django 4.1.7 on 2023-03-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='users',
        ),
    ]
