# Generated by Django 4.1.7 on 2023-03-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0002_rename_user_info_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='u_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
    ]
