# Generated by Django 4.1.7 on 2023-04-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0003_rename_e_mail_users_email_rename_pwd_users_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('ddl', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('coursedescription', models.TextField()),
                ('gradedistribution', models.JSONField()),
                ('creatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
                ('enrolllist', models.ManyToManyField(related_name='enrolllist', to='hydra_learning_management_system.users')),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('createtime', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('multimedia', models.CharField(max_length=50)),
                ('likes', models.IntegerField()),
                ('editted', models.BooleanField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
                ('creatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
                ('flagged', models.ManyToManyField(related_name='flagged', to='hydra_learning_management_system.users')),
                ('replyments', models.ManyToManyField(related_name='replyments', to='hydra_learning_management_system.users')),
            ],
        ),
        migrations.CreateModel(
            name='quizzes',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('ddl', models.CharField(max_length=100)),
                ('q1', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='replyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.posts')),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('fileapath', models.CharField(max_length=50)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
            ],
        ),
        migrations.CreateModel(
            name='enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
            ],
        ),
        migrations.CreateModel(
            name='assesments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.JSONField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
            ],
        ),
    ]
