# Generated by Django 4.1.7 on 2023-04-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0006_alter_assignments_ddl_alter_assignments_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='ans',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='ddl',
            field=models.DateTimeField(),
        ),
    ]
