# Generated by Django 4.1.7 on 2023-04-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0007_alter_quizzes_ans_alter_quizzes_ddl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesments',
            name='grade',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='enrolllist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='gradedistribution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='flagged',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='privacy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='replyments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='ans',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='q1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='q2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='q3',
            field=models.TextField(),
        ),
    ]
