# Generated by Django 4.1.7 on 2023-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0008_alter_assesments_grade_alter_courses_enrolllist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createtime',
            field=models.DateTimeField(),
        ),
    ]
